######################################################################
# Automatically generated by qmake (3.1) Sat Dec 6 13:39:48 2025
######################################################################

INCLUDEPATH += .
QT += widgets

# Input
HEADERS += MainWindow.hpp GraphicsTest.hpp
SOURCES += main.cpp MainWindow.cpp GraphicsTest.cpp
